### ISSUE TITLE
Flip active/not-active status for homekit main screen

### ISSUE THREAD

**Issue by dinof40** [jvmahon/homebridge-smartshades#4]
Excellent app and thank you for your time producing and sharing it.

I woudl like to make a recommendation to flip the active/not-active status, as the app always shows as white on the homekit screen. When you have many other systems running on this screen it's great that the white screen represents on, but this isn't the case with the blinds. It would be preferble for this to be shown as inactive.

**Comment by jvmahon** [comment]
I don't think I can do that.

When I wrote the app, I was trying to take care of a particular issue with HomeKit and my shade motors.  Specifically, for shade motors that only have one-way radio control, the NEO controller and HomeKit can't track if the shade is open or closed because another remote or device could have changed the position. To deal with this, I chose to always set HomeKit to view the shade as being at 50% - i.e., neither opened or closed. This then lets a user move the control slider up to open / down to close the shade (and a few seconds after sending the command, it gets reset to the 50% level).  If I wanted to show the icon as inactive, I'd have to always set it to 0%, but that means the user couldn't close the shade if it were opened.

**Comment by Mattserati** [comment]
Is it not possible to have a state/stateless option within the plugin, similar to the way Wemo Maker can be added?
I plan on only using HomeKit to open/close the blinds, so having the plugin assume the last requested state would be ideal for me, and enable HomeKit to identify whether the blinds were open or closed.
